spring.application.name=dobi

server.port=8080
spring.datasource.url=jdbc:postgresql://dpg-d85h9s7aqgkc73bcjom0-a.oregon-postgres.render.com/dobi_company2
spring.datasource.username=dobi_company2_user
spring.datasource.password=l9b47kRjQ2NhDHb8yoGkSmoNDAOA7S29
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/dobi/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
