spring.application.name=dobi

server.port=8080
spring.datasource.url=jdbc:postgresql://dpg-d7ef02cvikkc73eof1og-a.oregon-postgres.render.com/dobi_company_nhno
spring.datasource.username=dobi_company_nhno_user
spring.datasource.password=Ri7DSySp9RTdDcGZ5uiabW6IaXPKUhIV
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/dobi/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true